// Version

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: modules/book/bookPb/bookPb.proto

package bookPb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Structure
type FindBooksInIdsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *FindBooksInIdsReq) Reset() {
	*x = FindBooksInIdsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_book_bookPb_bookPb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindBooksInIdsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindBooksInIdsReq) ProtoMessage() {}

func (x *FindBooksInIdsReq) ProtoReflect() protoreflect.Message {
	mi := &file_modules_book_bookPb_bookPb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindBooksInIdsReq.ProtoReflect.Descriptor instead.
func (*FindBooksInIdsReq) Descriptor() ([]byte, []int) {
	return file_modules_book_bookPb_bookPb_proto_rawDescGZIP(), []int{0}
}

func (x *FindBooksInIdsReq) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type FindBooksInIdsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Books []*Book `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
}

func (x *FindBooksInIdsRes) Reset() {
	*x = FindBooksInIdsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_book_bookPb_bookPb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindBooksInIdsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindBooksInIdsRes) ProtoMessage() {}

func (x *FindBooksInIdsRes) ProtoReflect() protoreflect.Message {
	mi := &file_modules_book_bookPb_bookPb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindBooksInIdsRes.ProtoReflect.Descriptor instead.
func (*FindBooksInIdsRes) Descriptor() ([]byte, []int) {
	return file_modules_book_bookPb_bookPb_proto_rawDescGZIP(), []int{1}
}

func (x *FindBooksInIdsRes) GetBooks() []*Book {
	if x != nil {
		return x.Books
	}
	return nil
}

type Book struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title    string  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Price    float64 `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	ImageUrl string  `protobuf:"bytes,4,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	Damage   int32   `protobuf:"varint,5,opt,name=damage,proto3" json:"damage,omitempty"`
}

func (x *Book) Reset() {
	*x = Book{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_book_bookPb_bookPb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_modules_book_bookPb_bookPb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_modules_book_bookPb_bookPb_proto_rawDescGZIP(), []int{2}
}

func (x *Book) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Book) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Book) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

var File_modules_book_bookPb_bookPb_proto protoreflect.FileDescriptor

var file_modules_book_bookPb_bookPb_proto_rawDesc = []byte{
	0x0a, 0x20, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x2f, 0x62,
	0x6f, 0x6f, 0x6b, 0x50, 0x62, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x50, 0x62, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x25, 0x0a, 0x11, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x49,
	0x6e, 0x49, 0x64, 0x73, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x30, 0x0a, 0x11, 0x46, 0x69, 0x6e,
	0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x49, 0x6e, 0x49, 0x64, 0x73, 0x52, 0x65, 0x73, 0x12, 0x1b,
	0x0a, 0x05, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e,
	0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x05, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x22, 0x76, 0x0a, 0x04, 0x42,
	0x6f, 0x6f, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x64,
	0x61, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x64, 0x61, 0x6d,
	0x61, 0x67, 0x65, 0x32, 0x4b, 0x0a, 0x0f, 0x62, 0x6f, 0x6f, 0x6b, 0x47, 0x72, 0x70, 0x63, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x0e, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x6f,
	0x6f, 0x6b, 0x73, 0x49, 0x6e, 0x49, 0x64, 0x73, 0x12, 0x12, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x42,
	0x6f, 0x6f, 0x6b, 0x73, 0x49, 0x6e, 0x49, 0x64, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x46,
	0x69, 0x6e, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x49, 0x6e, 0x49, 0x64, 0x73, 0x52, 0x65, 0x73,
	0x42, 0x1c, 0x5a, 0x1a, 0x74, 0x61, 0x6e, 0x73, 0x61, 0x6e, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x73, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x50, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_modules_book_bookPb_bookPb_proto_rawDescOnce sync.Once
	file_modules_book_bookPb_bookPb_proto_rawDescData = file_modules_book_bookPb_bookPb_proto_rawDesc
)

func file_modules_book_bookPb_bookPb_proto_rawDescGZIP() []byte {
	file_modules_book_bookPb_bookPb_proto_rawDescOnce.Do(func() {
		file_modules_book_bookPb_bookPb_proto_rawDescData = protoimpl.X.CompressGZIP(file_modules_book_bookPb_bookPb_proto_rawDescData)
	})
	return file_modules_book_bookPb_bookPb_proto_rawDescData
}

var file_modules_book_bookPb_bookPb_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_modules_book_bookPb_bookPb_proto_goTypes = []interface{}{
	(*FindBooksInIdsReq)(nil), // 0: FindBooksInIdsReq
	(*FindBooksInIdsRes)(nil), // 1: FindBooksInIdsRes
	(*Book)(nil),              // 2: Book
}
var file_modules_book_bookPb_bookPb_proto_depIdxs = []int32{
	2, // 0: FindBooksInIdsRes.books:type_name -> Book
	0, // 1: bookGrpcService.FindBooksInIds:input_type -> FindBooksInIdsReq
	1, // 2: bookGrpcService.FindBooksInIds:output_type -> FindBooksInIdsRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_modules_book_bookPb_bookPb_proto_init() }
func file_modules_book_bookPb_bookPb_proto_init() {
	if File_modules_book_bookPb_bookPb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_modules_book_bookPb_bookPb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindBooksInIdsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_book_bookPb_bookPb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindBooksInIdsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_book_bookPb_bookPb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Book); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_modules_book_bookPb_bookPb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_book_bookPb_bookPb_proto_goTypes,
		DependencyIndexes: file_modules_book_bookPb_bookPb_proto_depIdxs,
		MessageInfos:      file_modules_book_bookPb_bookPb_proto_msgTypes,
	}.Build()
	File_modules_book_bookPb_bookPb_proto = out.File
	file_modules_book_bookPb_bookPb_proto_rawDesc = nil
	file_modules_book_bookPb_bookPb_proto_goTypes = nil
	file_modules_book_bookPb_bookPb_proto_depIdxs = nil
}
